-- Seed sample data for development

-- Insert sample leaders
INSERT INTO leaders (
  profile_id, 
  title, 
  company, 
  experience_description, 
  expertise_areas, 
  successful_exits, 
  companies_founded, 
  total_funding_raised,
  mentorship_areas,
  availability_status,
  hourly_rate,
  consultation_types,
  achievements,
  is_verified,
  rating,
  total_reviews
) VALUES
(
  (SELECT id FROM profiles WHERE full_name = 'Sarah Chen' LIMIT 1),
  'Serial Entrepreneur & Climate Tech Expert',
  'GreenTech Ventures',
  'Founded 3 successful climate tech startups with combined valuation of $500M+. Expert in sustainable technology, fundraising, and scaling green businesses.',
  ARRAY['Climate Tech', 'Fundraising', 'Product Strategy', 'Team Building', 'B2B Sales'],
  2,
  3,
  '$50M+',
  ARRAY['Early-stage startups', 'Climate tech', 'Fundraising strategy', 'Product-market fit'],
  'available',
  '$200/hour',
  ARRAY['mentorship', 'advisory', 'investment'],
  ARRAY['Forbes 30 Under 30', 'TechCrunch Disrupt Winner', 'Climate Innovation Award'],
  true,
  4.9,
  47
),
(
  (SELECT id FROM profiles WHERE full_name = 'Alex Rodriguez' LIMIT 1),
  'FinTech Innovator & Former Goldman Sachs VP',
  'NextGen Finance',
  'Led digital transformation at Goldman Sachs, then founded 2 FinTech unicorns. Deep expertise in financial services, blockchain, and regulatory compliance.',
  ARRAY['FinTech', 'Blockchain', 'Regulatory Compliance', 'Digital Banking', 'Investment Strategy'],
  1,
  2,
  '$200M+',
  ARRAY['FinTech startups', 'Regulatory strategy', 'Fundraising', 'Technical architecture'],
  'available',
  '$300/hour',
  ARRAY['mentorship', 'advisory', 'investment'],
  ARRAY['FinTech Innovator of the Year', 'Blockchain Pioneer Award', 'Top 40 Under 40'],
  true,
  4.8,
  32
),
(
  (SELECT id FROM profiles WHERE full_name = 'Maya Patel' LIMIT 1),
  'AI/ML Expert & Former Google Research',
  'AI Innovations Lab',
  'Led AI research at Google for 8 years, published 50+ papers, and founded an AI startup acquired by Microsoft for $300M.',
  ARRAY['Artificial Intelligence', 'Machine Learning', 'Computer Vision', 'NLP', 'Technical Leadership'],
  1,
  1,
  '$300M',
  ARRAY['AI/ML startups', 'Technical strategy', 'Research & development', 'Team scaling'],
  'busy',
  '$400/hour',
  ARRAY['mentorship', 'advisory'],
  ARRAY['Google Research Excellence Award', 'AI Pioneer Recognition', 'Top AI Researcher'],
  true,
  5.0,
  28
);

-- Insert sample tapris with proper creator relationships
INSERT INTO tapris (
  creator_id,
  title,
  slug,
  tagline,
  description,
  problem_statement,
  solution_approach,
  target_audience,
  mission,
  vision,
  category,
  stage,
  location,
  team_size,
  open_positions,
  required_skills,
  website,
  commitment_level,
  funding_stage,
  status,
  views,
  applications_count,
  featured
) VALUES
(
  (SELECT id FROM profiles WHERE full_name = 'Sarah Chen' LIMIT 1),
  'EcoTech Marketplace',
  'ecotech-marketplace',
  'Connecting consumers with verified sustainable products',
  'Revolutionary platform that uses AI to verify sustainability claims and connects eco-conscious consumers with genuinely green products. We solve the greenwashing problem while making sustainable shopping effortless.',
  'Climate change is accelerating, but consumers struggle to find and verify truly sustainable products. 73% of consumers want to buy sustainable products, but 68% don''t trust sustainability claims due to widespread greenwashing.',
  'We''re building an AI-powered verification system that analyzes supply chains, certifications, and environmental impact data to score products. Our marketplace only features verified sustainable products with transparent impact metrics.',
  'Environmentally conscious millennials and Gen Z consumers aged 18-35 who prioritize sustainability but struggle with greenwashing and lack of transparency in current marketplaces.',
  'To make sustainable living accessible and trustworthy for everyone',
  'A world where every purchase contributes to environmental restoration',
  'Climate Tech',
  'MVP',
  'San Francisco, CA',
  4,
  3,
  ARRAY['React', 'Node.js', 'Python', 'Machine Learning', 'UI/UX Design', 'Sustainability Expert'],
  'https://ecotech-marketplace.com',
  'Full-time',
  'Seed',
  'approved',
  1247,
  23,
  true
),
(
  (SELECT id FROM profiles WHERE full_name = 'Alex Rodriguez' LIMIT 1),
  'DeFi Banking Revolution',
  'defi-banking-revolution',
  'Traditional banking meets decentralized finance',
  'Next-generation banking platform that combines the security of traditional banking with the innovation of DeFi. Offering yield farming, crypto lending, and fiat-crypto bridges for the next generation of digital natives.',
  'Traditional banks offer 0.01% interest while DeFi protocols offer 5-15% APY, but DeFi is too complex and risky for average users. There''s a massive gap between traditional finance and decentralized finance.',
  'We''re building a regulated banking platform that abstracts away DeFi complexity while providing higher yields. Users get traditional banking UX with DeFi returns, backed by institutional-grade security and insurance.',
  'Tech-savvy millennials and Gen Z who want higher returns on their savings but find current DeFi too complex or risky. Target: 25-40 year olds with $10K+ in savings.',
  'To democratize access to high-yield financial products',
  'The bridge between traditional finance and the decentralized future',
  'FinTech',
  'Prototype',
  'New York, NY',
  6,
  4,
  ARRAY['Solidity', 'React Native', 'Node.js', 'Blockchain', 'Financial Compliance', 'Security'],
  'https://defibank.io',
  'Full-time',
  'Series A',
  'approved',
  892,
  31,
  true
),
(
  (SELECT id FROM profiles WHERE full_name = 'Maya Patel' LIMIT 1),
  'AI Content Studio',
  'ai-content-studio',
  'Hollywood-quality content creation powered by AI',
  'AI-powered platform that democratizes high-quality video content creation. From script to screen in minutes, not months. Perfect for creators, marketers, and businesses who want professional content without the Hollywood budget.',
  'Creating high-quality video content requires expensive equipment, skilled teams, and months of production time. 89% of marketers want to create more video content but are limited by budget and complexity.',
  'Our AI platform handles scriptwriting, voice generation, video editing, and post-production automatically. Users input their ideas and get professional-quality videos in minutes, with customizable styles and branding.',
  'Content creators, digital marketers, small businesses, and educational institutions who need high-quality video content but lack the resources for traditional production.',
  'To democratize professional content creation for everyone',
  'A world where anyone can create Hollywood-quality content',
  'AI/ML',
  'Growth',
  'Remote',
  8,
  2,
  ARRAY['Python', 'TensorFlow', 'Computer Vision', 'NLP', 'React', 'Video Processing'],
  'https://aicontentstudio.ai',
  'Full-time',
  'Series B',
  'approved',
  2156,
  18,
  false
);

-- Insert leader-tapri relationships
INSERT INTO leader_tapris (leader_id, tapri_id, role, equity_percentage) VALUES
(
  (SELECT l.id FROM leaders l JOIN profiles p ON l.profile_id = p.id WHERE p.full_name = 'Sarah Chen' LIMIT 1),
  (SELECT id FROM tapris WHERE slug = 'ecotech-marketplace' LIMIT 1),
  'Founder & CEO',
  45.0
),
(
  (SELECT l.id FROM leaders l JOIN profiles p ON l.profile_id = p.id WHERE p.full_name = 'Alex Rodriguez' LIMIT 1),
  (SELECT id FROM tapris WHERE slug = 'defi-banking-revolution' LIMIT 1),
  'Founder & CEO',
  40.0
),
(
  (SELECT l.id FROM leaders l JOIN profiles p ON l.profile_id = p.id WHERE p.full_name = 'Maya Patel' LIMIT 1),
  (SELECT id FROM tapris WHERE slug = 'ai-content-studio' LIMIT 1),
  'Founder & CTO',
  35.0
),
(
  (SELECT l.id FROM leaders l JOIN profiles p ON l.profile_id = p.id WHERE p.full_name = 'Alex Rodriguez' LIMIT 1),
  (SELECT id FROM tapris WHERE slug = 'ecotech-marketplace' LIMIT 1),
  'Advisor',
  2.0
),
(
  (SELECT l.id FROM leaders l JOIN profiles p ON l.profile_id = p.id WHERE p.full_name = 'Maya Patel' LIMIT 1),
  (SELECT id FROM tapris WHERE slug = 'defi-banking-revolution' LIMIT 1),
  'Technical Advisor',
  1.5
);
